#!/bin/bash
#BSUB -J JOB_NAME_score
#BSUB -n 1
#BSUB -R rusage[mem=8]
#BSUB -R span[hosts=1]
#BSUB -W 4:00
#BSUB -o /home/chayas/job_output/JOB_NAME_score_selected.stdout
#BSUB -eo /home/chayas/job_output/JOB_NAME_score_selected.stderr

source /home/chayas/.bashrc
conda activate qcf-manager-openff

python /data/chodera/chayas/fragmenter_examples/combinatorial_fragmentation/rank_fragments/rescore_selected_molecules.py  -n JOB_NAME
