#!/bin/bash
#BSUB -J JOB_NAME_combinde
#BSUB -n 1
#BSUB -R rusage[mem=24]
#BSUB -R span[hosts=1]
#BSUB -W 12:00
#BSUB -o /home/chayas/job_output/JOB_NAME_combine.stdout
#BSUB -eo /home/chayas/job_output/JOB_NAME_combine.stderr

source /home/chayas/.bashrc
conda activate qcf-manager-openff

python /data/chodera/chayas/fragmenter_examples/combinatorial_fragmentation/fragment_bond_orders/combine_fragments.py  -n JOB_NAME
