#!/bin/bash
#BSUB -J JOB_NAME_wbo
#BSUB -n 1
#BSUB -R rusage[mem=16]
#BSUB -R span[hosts=1]
#BSUB -W 72:00
#BSUB -o /home/chayas/job_output/JOB_NAME_oe_wbo.stdout
#BSUB -eo /home/chayas/job_output/JOB_NAME_oe_wbo.stderr

source /home/chayas/.bashrc
conda activate qcf-manager-openff

python /data/chodera/chayas/fragmenter_examples/combinatorial_fragmentation/fragment_bond_orders/compute_oe_wbo.py -i $LS_EXECCWD/../../fragment/validation_set/fragments_JOB_NAME.json -n JOB_NAME

