#!/bin/bash
#BSUB -J JOB_NAME_parent
#BSUB -n 1
#BSUB -R rusage[mem=8]
#BSUB -R span[hosts=1]
#BSUB -W 72:00
#BSUB -o /home/chayas/job_output/JOB_NAME.stdout
#BSUB -eo /home/chayas/job_output/JOB_NAME.stderr

source /home/chayas/.bashrc
conda activate qcf

python /data/chodera/chayas/fragmenter_examples/combinatorial_fragmentation/fragment_bond_orders/mini_drug_bank/compute_oe_wbo_parent_mini_drug_bank.py -n JOB_NAME

