#!/bin/bash
#BSUB -J JOB_NAME_wbo
#BSUB -n 1
#BSUB -R rusage[mem=32]
#BSUB -R span[hosts=1]
#BSUB -W 24:00
#BSUB -o /home/chayas/job_output/JOB_NAME_score_frags.stdout
#BSUB -eo /home/chayas/job_output/JOB_NAME_score_frags.stderr

source /home/chayas/.bashrc
conda activate qcf-manager-openff

python /data/chodera/chayas/fragmenter_examples/combinatorial_fragmentation/rank_fragments/validation_set/score_fragments.py -i $LS_EXECCWD/../../fragment_bond_order/validation_set/JOB_NAME_oe_wbo_by_bond.json -n JOB_NAME

